pub mod catalog;
pub mod error;
pub mod fuzzy;
pub mod geometry;
pub mod ids;
pub mod package_manager;
pub mod pane;
pub mod run_command;
pub mod sidebar_decision;

pub const PLUGIN_ID: &str = "herdr-npm";
pub const PANE_ENTRYPOINT: &str = "sidebar";
pub const SIDEBAR_LABEL: &str = "npm";
pub const SIDEBAR_TOKEN_KEY: &str = "herdr_npm_sidebar";
pub const SIDEBAR_TOKEN_VALUE: &str = "v1";
pub const EXPLORER_TOKEN_KEY: &str = "herdr-sidebar-explorer";
pub const PREFERRED_OUTER_COLUMNS: u16 = 32;
pub const MIN_SIDEBAR_SHARE: f64 = 0.15;
pub const MAX_SIDEBAR_SHARE: f64 = 0.50;
pub const ORIGIN_WORKSPACE_ENV: &str = "HERDR_NPM_ORIGIN_WORKSPACE";
pub const ORIGIN_TAB_ENV: &str = "HERDR_NPM_ORIGIN_TAB";
pub const ORIGIN_PANE_ENV: &str = "HERDR_NPM_ORIGIN_PANE";
pub const ORIGIN_FOREGROUND_CWD_ENV: &str = "HERDR_NPM_ORIGIN_FOREGROUND_CWD";
pub const ORIGIN_CWD_ENV: &str = "HERDR_NPM_ORIGIN_CWD";
pub const CWD_FALLBACK_NOTE: &str = "Current directory unavailable; using pane start directory";
